steps:
- name: node:14.21.3
  entrypoint: npm
  args: ['install']
- name: node:14.21.3
  volumes:
  - name: 'cred_vol'
    path: '/builder/home/.credentials'
  entrypoint: 'bash'
  args:
    - '-c'
    - | 
        echo '{}' > /builder/home/.credentials/SmartFinance-Bills-Beta-eb6d6507173d.json
- name: node:14.21.3
  entrypoint: npm
  args: ['test']
  volumes:
  - name: 'cred_vol'
    path: '/builder/home/.credentials'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sfinbills:v0', '.']
images: ['gcr.io/$PROJECT_ID/sfinbills:v0']
